### PR TITLE
React-native-web compatiblity

### PR DESCRIPTION
**Pull request by PeterKottas**
Hi I am working on making https://github.com/FaridSafi/react-native-gifted-chat compatible with react-native-web. One of the problems I encountered was with this lib. It needs web implementation and as I see it, the android one fits in quite nicely. All I did was to reexport that. Let me know if that's ok with you. I'll be thrilled to see this release asap so I am happy to help if you need it. Cheers!

### CODE REVIEW

**Comment by peterpme** [comment]
@brentvatne how do you feel about web support?

**Comment by c-goettert** [comment]
I think you should use 
```
import ActionSheet from './ActionSheet.android.js'
export default ActionSheet
```
to be compliant with default webpack-config of Create-React-App (which is obviously a nice thing if you want to be web compliant anyway). The commited syntax will break as you can see [here](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29lQgWzgHIA6AegEEBjGASwgDsBlAC2GBhNQYT1oRIArAM5EA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)  (you need to activate stage 1 to make it compile, which is currently not default in create-react-app).

**Comment by c-goettert** [comment]
actually, to make it web-compliant node-modules shouldn't use any ES6 syntax but should use `require` & `module.exports` syntax. Create-React-App excludes `node_modules` folder from babel compilation by default, so any non-standard syntax will cause compile errors on web.

**Comment by peterpme** [comment]
Web support will not happen for the forseeable future. Thank you

**Pull request closed without merging**
