### PR TITLE
Migrate ActionSheetIOS API from react-native core 

### PR DESCRIPTION
**Pull request by nd-02110114**
## What I did

I migrated ActionSheetIOS API  from RN Core by following [this instruction](https://github.com/facebook/react-native/issues/23313#issuecomment-461462981) 
This work is related to [this issues (Lean Core)](https://github.com/facebook/react-native/issues/23313)

**TODO List** 
- [x] setup native library environment by using https://github.com/frostney/react-native-create-library
- [x] Create `js` directory and move js code of the ActionSheetIOS API from RN Core
- [x] Move native code of the ActionSheetIOS API  from RN Core
- [x] Move RNTesterExample from RN to example 
- [x] Introduce eslint and prettier
- [x] Check ActionSheetIOS API by using RNTesterExample
- [x] Move previous ActionSheet code(by Expo) to `js` directory
- [x] Move previous example code(by Expo) to `example` directory
- [x] Apply flow check to all js files
- [x] Improving Typings(For TypeScript)
- [x] Update README.md (partially)
- [x] Check all example code by using iOS and Android simulator 
- [ ] Check example code by using web browser  
- [ ] Improve READNE.md 
- [ ] Write test for js code (example: [WebView](https://github.com/react-native-community/react-native-webview/blob/master/js/__tests__/WebViewShared-test.js))
- [ ] Setting for npm publish (For example, `.npmignore`, `package.json`, ....)
- [ ] Add CI 

**Notion**
Now I got this error when the example app stands, but I think expo-assets (@expo/vector-icon) causes this bug. So, I don't care.... Action Sheet API itself is no problem. 
```
`expo-assets` requires `expo-file-system` package to be installed and linked
```

### CODE REVIEW

**Comment by nd-02110114** [comment]
@cpojer @brentvatne @EvanBacon @peterpme 
I migrated  ActionSheetIOS API from react-native core. 
Let me know if something is missing or wrong  🙇

**Comment by peterpme** [comment]
Hey @nd-02110114,

How exciting 😍 Thank you!

This is a very loaded PR and there are several things that need to be addressed first.

- Flowtype v. Typescript. Expo has been moving forward with Typescript in core, so this sounds like the right time to convert, but that includes stripping out all the Flowtype stuff (ideally in 1 easily readable commit) cc @brentvatne 

- Native implementation. This _has_ been using a purely JS implementation. We could utilize this, but we'd move the native implementation to core and refer to it here cc @ide

- Eslint / styling rules? Let's go with Expo's styles here and remove the ones you've added (unless they are Expos)

- Using Expo's version of React Native (once the native module stuff is squared away)

**Comment by nd-02110114** [comment]
@peterpme 
I'msorry to replay so late 🙇(I took a vacation) 
 
I could understand your direction !
So, I make the roadmap for migrating ActionSheetIOS again.

- [ ] 1. Convert  from flow to TS
    (care about Using Expo's version of React Native and Eslint / styling rule) 
- [ ] 2. Migrate native api from react-native repo to expo(maybe here https://github.com/expo/expo ...?)

Therefore, I want to start converting from flow to TS. 
Is it OK...?  If there is no problem, i will start converting !!

**Comment by peterpme** [comment]
@EvanBacon whats the status on flowtype vs. typescript in expo? do you want both, or just one or the other?

**Comment by brentvatne** [comment]
just typescript

**Comment by ide** [comment]
> Flowtype v. Typescript

Just TypeScript since the entire Expo SDK is now moved to TypeScript and we'd rather put all of our typed-JS energy into making TS work well over the long run rather than splitting our energy.



For the TS config, we aren't ready to publish the one from the Expo repo but this is what it looks like: https://github.com/expo/expo/blob/master/packages/expo-module-scripts/tsconfig.base.json. Some of the stuff around Jest and ts-declarations might not be needed for this repo for now.

> Native implementation.

I think we should use the native iOS action sheet, specifically the modern API. When RN was first written many years ago, there was an older, awkward native action sheet API. Throwing out the old API and just focusing on the new one I think will be better.

> Eslint / styling rules?

Right now, we don't have an ESLint config that works with TypeScript. Our styling rules are what Prettier emits with this config: https://github.com/expo/expo/blob/master/.prettierrc. Run with this for now.

Longer term, we hope to get our ESLint config working with TypeScript (should be much easier since TSLint is spiritually merging into ESLint). It will mostly delegate styling to Prettier with the config linked above, and have other linting rules that work across JS and TS, plus linting rules for React hooks.

**Comment by nd-02110114** [comment]
@ide

**Comment by nd-02110114** [comment]
closed by #110

**Pull request closed without merging**
