### PR TITLE
Add support for `title` and `message` in Android

### PR DESCRIPTION
**Pull request by ghost**
iOS ActionSheet has native support for optional `title` and `message` props, which look like this:
screen shot 2016-12-02 at 2 33 56 pm

This adds support for a similar UI in the Android version:
screenshot_20161202-165621

### CODE REVIEW

**Comment by sibelius** [comment]
@brentvatne this looks good

**Comment by jesperlndk** [comment]
Let's get this in! cc: @brentvatne

**Comment by chris-divvito** [comment]
Is this PR or some other method of support for the title prop likely to be added anytime soon? seems to have stalled

**Comment by peterpme** [comment]
@chris-divvito if you're willing to fix this merge conflict and make sure this is working correctly, I'd be happy to merge it in!

**Comment by jstheoriginal** [comment]
if someone wants to test this, it should be good to go: https://github.com/expo/react-native-action-sheet/pull/78

**Comment by JulianKingman** [comment]
Is there a problem with this PR? I'd love to see this merged.

**Comment by peterpme** [comment]
@JulianKingman I'll test this tomorrow and merge it in then if it works.

**Comment by peterpme** [comment]
Closing due to #78

**Pull request closed without merging**
