### PR TITLE
Update deprecated React.PropTypes references

### PR DESCRIPTION
**Pull request by cooperka**
Update deprecated `React.PropTypes` references to use external `prop-types` lib. Deprecated since React v15.5.0, see [release notes](https://github.com/facebook/react/releases/tag/v15.5.0) for more info. This change should not be breaking 🌴 

Also committed the auto-generated `yarn.lock` file. I assume that's fine, but feel free to remove that commit if you'd rather not have it for any reason.

### CODE REVIEW

**Comment by kennydee** [comment]
Hi everyone, 

Any news on that one ? it seems that this is the only package we use which is not yet uptodate.

Thanks

**Comment by cooperka** [comment]
Hi @kennydee, feel free to make a change like this to fix it in the meantime: https://github.com/FaridSafi/react-native-gifted-chat/commit/9e2043addc98b9560110ff00c5a878dff01be439

**Comment by xcarpentier** [comment]
See PR #59

**Comment by cooperka** [comment]
Thanks @xcarpentier!

**Pull request closed without merging**
