### PR TITLE
Icons for menus with component

### PR DESCRIPTION
**Pull request by tofoli**

### CODE REVIEW

**Comment by peterpme** [comment]
Hey @tofoli,

thanks for the addition! This was just merged in another branch 😄

**Comment by tofoli** [comment]
Hey @peterpme,

I'm sorry, maybe it was not clear.
I know, but only one image is allowed, the change I made allows element. For example:

```js
this._actionSheetRef.showActionSheetWithOptions({
  options: ['Take Picture', 'Select Photo', 'Cancel'],
  icons: [
    <Icon name="camera" style={styles.iconActionSheet} />,
    <Icon name="images" style={styles.iconActionSheet} />,
    <Icon name="close" style={{...styles.iconActionSheet, color: brandDanger}} />,
  ],
  cancelButtonIndex: 2,
}
```

**Comment by peterpme** [comment]
Hey @tofoli,

Did you happen to try the new version? What happens when you pass in an array of icons?

**Comment by tofoli** [comment]
Yes @peterpme,

package.json
```json
  "dependencies": {
    "@expo/react-native-action-sheet": "expo/react-native-action-sheet",
    "expo": "^25.0.0",
    "native-base": "^2.3.9",
    "react": "16.2.0",
    "react-native": "0.52.0"
  }
```

App.js
```js
import React, { Component } from 'react';
import { Image } from 'react-native';
import { Text, View, Icon } from 'native-base';
import ActionSheet from '@expo/react-native-action-sheet';

export default class App extends Component {
  _onOpenActionSheetIcon = () => {
    this._actionSheetRef.showActionSheetWithOptions({
      textStyle: { color: 'black' },
      options: ['Icon - Take Picture', 'Icon - Select Photo', 'Icon - Cancel'],
      icons: [
        <Icon name="camera" />,
        <Icon name="images" />,
        <Icon name="close"  />,
      ],
      cancelButtonIndex: 2,
    });
  }
  
  _onOpenActionSheetImage = () => {
    this._actionSheetRef.showActionSheetWithOptions({
      textStyle: { color: 'black' },
      options: ['Image - Take Picture', 'Image - Select Photo', 'Image - Cancel'],
      icons: [
        {uri: 'https://image.flaticon.com/icons/png/128/3/3901.png'},
        {uri: 'https://image.flaticon.com/icons/png/128/263/263128.png'},
        {uri: 'https://image.flaticon.com/icons/png/128/52/52084.png'},
      ],
      cancelButtonIndex: 2,
    });
  }

  render() {
    return (
      <ActionSheet ref={_ref => this._actionSheetRef = _ref}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
          <Text style={{margin: 20}} onPress={this._onOpenActionSheetIcon}>Tap to Show Icon</Text>
          
          <Text style={{margin: 20}} onPress={this._onOpenActionSheetImage}>Tap to Show Image</Text>
        </View>
      </ActionSheet>
    );
  }
}
```

Tap to Show Image
whatsapp image 2018-03-01 at 11 04 11 2

Tap to Show Icon
whatsapp image 2018-03-01 at 11 04 11 1

**Comment by fukemy** [comment]
hi, i got error
***TypeError: undefined is not a function (near '..._this.ActionSheet.showActionSheetWithOptions...'***

**Pull request closed without merging**
