### PR TITLE
Supports nested ActionSheets in Android

### LINKED ISSUE #112: Android: Calling showActionSheetWithOptions from an action sheet selection results in a NOOP
If on select of an action sheet option you call another showActionSheetWithOptions nothing happens on android due to [isVisible](https://github.com/expo/react-native-action-sheet/blob/master/ActionSheet.js#L307) being true at the time. isVisible is only set to false after ~225ms which is the animation timing, which is before the onSelect is called. On iOS it properly pops the second sheet.

The only work around right now is to "save" the callback and call it within the onAnimationOut.

### PR DESCRIPTION
**Pull request by bradbumbalough**
- Closes #112

Since iOS is statically invoked, you can have nested ActionSheets out of the box. However, in the Android implementation it will bomb out when the second ActionSheet is called since it's currently visible .. see line below:

https://github.com/expo/react-native-action-sheet/blob/22753e0c0c765651403e6618069ccc8677738f5e/src/ActionSheet/index.tsx#L141

In this fix, if the ActionSheet is invoked while it's currently visible and animating (from closing), it will store the next invoke method in the class until it completes animating out.

### CODE REVIEW

**Comment by brentvatne** [comment]
does this scale up to n consecutive calls? `showActionSheetWithOptions(..); showActionSheetWithOptions(..); showActionSheetWithOptions(..); showActionSheetWithOptions(..); showActionSheetWithOptions(..);`

it seems like with this implementation it'll work only for one queued call, but i'm not the most familiar with the codebase in the current state so i may be wrong

**Comment by bradbumbalough** [comment]
@brentvatne thanks for checking this out! Yes, I tested this in my app where making a selection in the action sheet would open another action, that would just call itself again. So essentially an infinite loop. It does only handle one at a time, but I don't think you could have simultaneous action sheets displayed on the screen anyway. 

Also updated against master to resolve the conflict.

**Comment by brentvatne** [comment]
could you create a simple snack where i can test the current behavior on android and ios that this is expected to fix and compare them easily?

**Comment by bradbumbalough** [comment]
@brentvatne absolutely. Here's a simple one that will open multiple action sheets from itself. https://snack.expo.io/@bradbumbalough/thoughtful-waffles.

**Comment by brentvatne** [comment]
very reasonable change now that i see that snack, thank you @bradbumbalough for the patience and the explanation!

**Comment by brentvatne** [comment]
released in 3.2.0 🎉

**Pull request merged**
