### PR TITLE
Add TypeScript types

### PR DESCRIPTION
**Pull request by henrikra**
Ref: https://github.com/expo/react-native-action-sheet/issues/38

I started using this library with TS and noticed that this library doesn't have TS types. So that is why I made them :) I have also added tests for types

### CODE REVIEW

**Comment by peterpme** [comment]
Thank you @henrikra :heart:

**Comment by henrikra** [comment]
Great! Can you do new release?

**Comment by smkhalsa** [comment]
Hmm. It looks like I have 1.1.0 installed but still am getting an error about missing types. I also don't see the d.ts file in my node modules.

**Comment by henrikra** [comment]
@peterpme Can you check it 1.1.0 was succesful?

**Comment by peterpme** [comment]
@henrikra yes, there's been issues with npm. Just a sec

**Comment by dozoisch** [comment]
@peterpme I don't see any types shipped with 1.1.0

**Comment by dozoisch** [comment]
possibly due to https://github.com/expo/react-native-action-sheet/pull/92

**Pull request merged**
